version: "3"

services:
  web-server:
    build:
      context: ./bin/${PHP_VERSION}
    container_name: '${PROJECT_NAME}-${PHP_VERSION}'
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
  mysql-server:
    build:
      context: "./bin/${MYSQL_VERSION}"
    container_name: '${PROJECT_NAME}-${MYSQL_VERSION}'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: '${PROJECT_NAME}-phpmyadmin'
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
volumes:
  mysql-data: